### ISSUE TITLE
Unexpected placement and usage of WordPress link menus

### ISSUE THREAD

**Issue by pleia2** [knomepasi/ubuntu-community-wordpress-theme#6]
For ubuntu-california.org, we're using WordPress as a very basic series of static page for now since we don't yet have volunteers to maintain a proper blog. This works fine with the old Thematic-based community theme (which you can view by going to the live site today) where we are not exposing pages that aren't really used by us (like blog link, categories, rss feed, etc).

Even if I were using these links, or replaced them with the links we want, they are just showing up as a listing on the top of the page, which is not optimal for us. See the screenshot.

![ubuntu-california-test-knome-theme](https://cloud.githubusercontent.com/assets/879924/12876698/4743b30c-cdba-11e5-8ce0-627afc819da4.png)

Also, it ignores all links in menus I _think_ were set up with the old Thematic theme. This may just be something that needs to be documented when people make the switch.

**Comment by knomepasi** [comment]
The first issue you are describing is caused by how WordPress handles widget areas (sidebars etc.) and widgets; the first one will always show the default widgets. (The default widgets include the meta links, like the ones in your screenshot.) In this case, the first widget area is the notification area, where you are mostly supposed to be adding text area widgets with short content. To fix the issue, simply remove the default widgets from the notification widget area.

I'll look into making another one as the first one. The only drawback is that the first registered widget area also appears first on the widget editing page, which is why the order is what it is currently.

The second issue you mention (links in menus) is also related to the way WordPress handles widget areas. When you change the theme, WordPress will basically forget all settings for widget areas. This means you will have to set up the widget areas again. At least with later versions (4.x), this forgetting is theme-based; when you switch back to the old theme, you still have your settings intact.
